import sys
import os
import time
import re
import smtplib
import psutil
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

def is_valid_email(email):
    
    pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'
    return re.match(pattern, email) is not None

def generate_log_file(dir_name):
    
    if not os.path.exists(dir_name):
        os.makedirs(dir_name)

   
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    log_filename = f"ProcessLog_{timestamp}.log"
    log_path = os.path.join(dir_name, log_filename)

    try:
        with open(log_path, 'w', encoding='utf-8') as log_file:
            log_file.write("==================================================\n")
            log_file.write(f"Process Log Created At: {time.ctime()}\n")
            log_file.write("==================================================\n\n")
            log_file.write(f"{'PID':<10} {'Name':<30} {'Username':<20}\n")
            log_file.write("-" * 60 + "\n")

            for proc in psutil.process_iter(['pid', 'name', 'username']):
                try:
                    info = proc.info
                    pid = info['pid']
                    name = info['name'] or "N/A"
                    username = info['username'] or "N/A"
                    log_file.write(f"{pid:<10} {name:<30} {username:<20}\n")
                except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
                    continue

        print(f"[SUCCESS] Log file successfully created at: {log_path}")
        return log_path
    except Exception as e:
        print(f"[ERROR] Failed to create log file: {e}")
        sys.exit(1)

def send_email(receiver_email, attachment_path):
  
    
   
    sender_email = "your_email@gmail.com"      
    sender_password = "xxxx xxxx xxxx xxxx"     

    
    if sender_email == "your_email@gmail.com":
        print("\n[WARNING] Please set your 'sender_email' and 'sender_password' inside the script to send emails.")
        print("[INFO] Log file was created, but email step was skipped.\n")
        return

    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = receiver_email
    msg['Subject'] = "Process Automation Log File"

    body = "Respected Sir/Madam,\n\nPlease find the attached process log file generated by the Python automation script.\n\nThank you."
    msg.attach(MIMEText(body, 'plain'))

    try:
       
        with open(attachment_path, 'rb') as attachment:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(attachment.read())
            encoders.encode_base64(part)
            part.add_header('Content-Disposition', f"attachment; filename={os.path.basename(attachment_path)}")
            msg.attach(part)

        print("Connecting to Gmail SMTP server...")
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, receiver_email, msg.as_string())
        server.quit()
        
        print(f"[SUCCESS] Email successfully sent to {receiver_email}!")

    except smtplib.SMTPAuthenticationError:
        print("\n[ERROR] Email Authentication Failed!")
        print("Reason: Incorrect App Password or Email ID.")
        print("Tip: Use a 16-character App Password generated from Google Security settings.\n")
    except Exception as e:
        print(f"\n[ERROR] Failed to send email: {e}\n")

def main():
    
    if len(sys.argv) != 3:
        print("\n[ERROR] Invalid Arguments!")
        print("Usage: python ProcInfoLog.py <DirectoryName> <EmailID>")
        print("Example: python ProcInfoLog.py Demo Marvellousinfosystem@gmail.com\n")
        sys.exit(1)

    directory_name = sys.argv[1]
    recipient_email = sys.argv[2]

    if not is_valid_email(recipient_email):
        print(f"\n[ERROR] '{recipient_email}' is not a valid email address.\n")
        sys.exit(1)

    print("\nStarting Process Log Automation...")
    log_file_path = generate_log_file(directory_name)

    print(f"Sending email to {recipient_email}...")
    send_email(recipient_email, log_file_path)

if __name__ == "__main__":
    main()